### PR TITLE
fix(automerge): implement exponential backoff

### LINKED ISSUE #176: Automerge fails on some PRs when there are multiple PRs being merged in very short period of time
## Description

Sometimes GitHub rejects the api call to merge the PR.

## Expected Behaviour

Failed PR should be retried a few (configurable) times with (preferably) an exponential delay.
Failure could still be logged as a warning

## Actual Behaviour

Leaves the PR open and logs this message:
```
time="2024-05-14T15:32:53Z" level=error msg="Failed to merge PR: err=PUT https://api.github.com/repos/[REPO_OWNER]/[REPO_NAME]/pulls/4333/merge: 405 Base branch was modified. Review and try the merge again. []" prNumber=4331 repo=[REPO_OWNER]/[REPO_NAME]
```

## Affected Version

`v0.1.9`

## Steps to Reproduce

Run `telefonistka bump-regex --auto-merge ...` in a loop on the same repository.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair-incubator/telefonistka/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

### PR DESCRIPTION
**Pull request by Ben10k**
## Description

Retry mechanism with exponential backoff is implemented for automatically merging PRs.

Resolves #176

## Type of Change

- [x] Bug Fix
- [ ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair-incubator/telefonistka/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [x] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [x] All new and existing tests pass

### CODE REVIEW

File: internal/pkg/githubapi/github.go [hunk 1]
```diff
@@ -414,14 +415,39 @@ func handleMergedPrEvent(ghPrClientDetails GhPrClientDetails, prApproverGithubCl
...
+				}
+				return err
+			}
+			details.PrLogger.Errorf("Failed to merge PR: permanent err=%v", err)
+			return backoff.Permanent(err)
+		}
+		return nil
+	}
+
+	err := backoff.Retry(operation, backoff.NewExponentialBackOff())
```
Comment (Oded-B) [inline internal/pkg/githubapi/github.go:433]:
```suggestion
        // Using default values, see https://pkg.go.dev/github.com/cenkalti/backoff#pkg-constants
	err := backoff.Retry(operation, backoff.NewExponentialBackOff())
```

File: go.mod [hunk 2]
```diff
@@ -5,11 +5,9 @@ go 1.21
 require (
 	github.com/alexliesenfeld/health v0.8.0
 	github.com/bradleyfalzon/ghinstallation/v2 v2.10.0
+	github.com/cenkalti/backoff v2.2.1+incompatible
```
Comment (Oded-B) [inline go.mod:8]: The doc site shows `v2.2.1+incompatible`(From 2019?) as latest but their repo have v3.X.X and v4.X.X
Can we use the newer one?

File: internal/pkg/githubapi/github.go [hunk 3]
```diff
@@ -711,7 +738,7 @@ func createCommit(ghPrClientDetails GhPrClientDetails, treeEntries []*github.Tre
 		Tree:    tree,
 	}
 
-	commit, resp, err := ghPrClientDetails.GhClientPair.v3Client.Git.CreateCommit(ghPrClientDetails.Ctx, ghPrClientDetails.Owner, ghPrClientDetails.Repo, newCommitConfig)
+	commit, resp, err := ghPrClientDetails.GhClientPair.v3Client.Git.CreateCommit(ghPrClientDetails.Ctx, ghPrClientDetails.Owner, ghPrClientDetails.Repo, newCommitConfig, nil)
```
Comment (Ben10k) [inline internal/pkg/githubapi/github.go:741]: `CreateCommit`'s signature has changed since GH client v52 that requires an additional parameter for `CreateCommitOptions` which is used for signing messages

File: go.mod (hunk 2 above)
Comment (Ben10k) [reply go.mod]: Updated to the latest one

**Comment by Ben10k** [comment]
I'll fix the linting error, most likely tomorrow.
ot sure what to do with the failing docker build?

**Comment by Oded-B** [comment]
Yeah, the docker build is unrelated.
I'll try to take a look, but I will not block this pr if it's the only issue, worst case I'll validate it locally

**Comment by Ben10k** [comment]
@Oded-B linting issues fixed, can you approve workflows and tale a look?

**Review by Oded-B — APPROVED** [review]
